name: Add release label to PR and linked issues when PR gets merged            - name: Setup Node.js environment
  uses: actions/setup-node@v4.2.0
  with:
    # Set always-auth in npmrc.
    always-auth: # optional, default is false
    # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
    node-version: # optional
    # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
    node-version-file: # optional
    # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec.
    check-latest: # optional
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
    registry-url: # optional
    # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
    scope: # optional
    # Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
    cache: # optional
    # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional
          

on:
  pull_request:
    branches:
      - main
    types:
      - open

jobs:
  add-release-label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0 # This is needed to checkout all branches

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn --immutable
        working-directory: '.github/scripts'

      - name: Get the next semver version
        id: get-next-semver-version
        env:
          FORCE_NEXT_SEMVER_VERSION: ${{ vars.FORCE_NEXT_SEMVER_VERSION }}
        run: ./get-next-semver-version.sh "$FORCE_NEXT_SEMVER_VERSION"
        working-directory: '.github/scripts'

      - name: Add release label to PR and linked issues
        id: add-release-label-to-pr-and-linked-issues
        env:
          RELEASE_LABEL_TOKEN: ${{ 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 }}
          NEXT_SEMVER_VERSION: ${{ env.NEXT_SEMVER_VERSION }}
        run: yarn run add-release-label-to-pr-and-linked-issues
        working-directory: '.github/scripts'
